name: Java CI with PostgreSQL

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: fridaydb_user
          POSTGRES_PASSWORD: AewWVoggzLbZ5IDCTuZoHGqrSJc067in
          POSTGRES_DB: fridaydb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Build with Maven (no need for working-directory if pom.xml is at root)
      - name: Build with Maven
        run: mvn clean install
        working-directory: DivineCuisine 
       
        
      # Run tests
      - name: Run tests
        run: mvn test
